/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import DAO.TareaDAO;
import Modelos.Tarea;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tblTareas.getModel();
        tblTareas.setDefaultEditor(Object.class, null); // Desactiva edición de todas las celdas de la tabla
           cargarTareasEnTabla();
    }
    
    private void cargarTareasEnTabla() {
    TareaDAO dao = new TareaDAO();
    List<Tarea> tareas = dao.cargarTareasDesdeArchivos();

    DefaultTableModel modelo = (DefaultTableModel) tblTareas.getModel();
    modelo.setRowCount(0); // limpia la tabla antes de llenar

    int pos = 1;
    for (Tarea t : tareas) {
        modelo.addRow(new Object[]{
            pos++,                               // Posición
            t.getNombre(),                        // Nombre
            t.getId(),                            // ID
            t.getAsignatura(),                    // Asignatura
            t.getFechaInicio(),                   // Fecha de inicio
            t.getFechaEntrega(),                  // Fecha de entrega
            t.getPrioridad()                      // Prioridad
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        tituloTareas = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnActualizartarea = new javax.swing.JButton();
        btnAnadirtarea = new javax.swing.JButton();
        btnEliminartarea = new javax.swing.JButton();
        btnBuscartarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Posicion", "Nombre", "ID", "Asignatura", "Fecha de inicio", "Fecha de entrega", "Prioridad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTareas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 680, 150));

        tituloTareas.setBackground(new java.awt.Color(255, 255, 255));
        tituloTareas.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        tituloTareas.setForeground(new java.awt.Color(255, 255, 255));
        tituloTareas.setText("TAREAS");
        jPanel1.add(tituloTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 220, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 60, 40));

        btnActualizartarea.setText("Actualizar tarea");
        jPanel1.add(btnActualizartarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, 40));

        btnAnadirtarea.setText("Añadir tarea");
        btnAnadirtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirtareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnadirtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 40));

        btnEliminartarea.setText("Eliminar tarea");
        btnEliminartarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminartareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminartarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 110, 40));

        btnBuscartarea.setText("Buscar tarea");
        jPanel1.add(btnBuscartarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirtareaActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tblTareas.getModel();
   
        // Abrimos la ventana de Añadir tareas
    VentanaAñadirTarea ventanaAñadirTarea = new VentanaAñadirTarea(modelo);
    ventanaAñadirTarea.setVisible(true); 
    
    
    ventanaAñadirTarea.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosed(java.awt.event.WindowEvent e) {
        cargarTareasEnTabla(); // 🔁 Se actualiza y se reordena automáticamente
    }
});

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirtareaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
         // Abrimos la ventana principal
    Login login = new Login();
    login.setVisible(true);
    this.dispose(); // Cierra la ventana principal

// TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEliminartareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminartareaActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminartareaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizartarea;
    private javax.swing.JButton btnAnadirtarea;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscartarea;
    private javax.swing.JButton btnEliminartarea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTareas;
    private javax.swing.JLabel tituloTareas;
    // End of variables declaration//GEN-END:variables
}
